import "../App.css";

const Modal = () => {
  return (
    <div class="blk">
      <p class="is-size-6">
        {" "}
        This document contains the terms and conditions that govern your use of
        tl-dr, a platform that aggregates and analyzes user data from stock
        brokers, such as stock portfolios and recent trades, and uses this
        information to generate predictions based on news articles ingested from
        a given day. Please read this agreement carefully before using tl-dr. By
        using tl-dr, you agree to be bound by these terms and conditions.
      </p>
      <h2 class="is-size-5"> <b>1. Use of tl-dr</b> </h2>
      <p class="is-size-6">
        tl-dr is made available for your personal, non-commercial use only. You
        may not use tl-dr for any other purpose, including commercial purposes,
        without the prior written consent of tl-dr.{" "}
      </p>
      <h2 class="is-size-5"> <b>2. User Data </b></h2>
      <p class="is-size-6">
        {" "}
        tl-dr may collect, store and use user data, including but not limited
        to, stock portfolios and recent trades, in order to provide predictions
        based on news articles ingested from a given day. You agree to provide
        accurate, complete and current user data and to update such data as
        necessary. tl-dr may use your user data to provide you with personalized
        content.
      </p>
      <h3 class="is-size-5"> <b>3. Disclaimer of Liability </b></h3>
      <p class="is-size-6">
        {" "}
        tl-dr is provided on an "as is" and "as available" basis. tl-dr does not
        guarantee the accuracy, completeness or usefulness of the information
        provided through tl-dr, and you agree that tl-dr will not be liable for
        any errors or omissions in the information provided. The predictions
        generated by tl-dr are speculative in nature and should not be relied
        upon as actual investment advice. You should always consult with a
        licensed financial advisor before making any investment decisions.
      </p>
      <h3 class="is-size-5"> <b>4. Indemnification </b></h3>
      <p class="is-size-6">
        {" "}
        You agree to indemnify and hold tl-dr and its affiliates, officers,
        agents and employees harmless from any claim or demand, including
        reasonable attorney's fees, made by any third party due to or arising
        out of your use of tl-dr, your violation of these terms and conditions,
        or your violation of any rights of another person or entity.
      </p>
      <h3 class="is-size-5" > <b>5. Termination </b></h3>
      <p class="is-size-6">
        {" "}
        tl-dr reserves the right to terminate your access to tl-dr at any time
        and for any reason, without notice. Upon termination, you must
        immediately destroy all copies of any information obtained from tl-dr.
      </p>
      <h3 class="is-size-5"> <b>6. Governing Law</b> </h3>
      <p class="is-size-6">
        {" "}
        These terms and conditions shall be governed by and construed in
        accordance with the laws of the jurisdiction in which tl-dr is based,
        without giving effect to its conflict of laws provisions.
      </p>
      <h3 class="is-size-5"> <b>7. Changes to Terms and Conditions </b> </h3>
      <p class="is-size-6">
        {" "}
        tl-dr reserves the right to modify these terms and conditions at any
        time, and such modifications shall be effective immediately upon posting
        the modified agreement on tl-dr. Your continued use of tl-dr following
        the posting of the modified agreement shall be deemed to be your
        acceptance of the modified agreement.
      </p>
      <h3 class="is-size-5"><b>8. Entire Agreement </b></h3>
      <p class="is-size-6">
        {" "}
        These terms and conditions constitute the entire agreement between you
        and tl-dr and supersede all prior agreements and understandings, whether
        written or oral, relating to the use of tl-dr.
      </p>
      <h3 class="is-size-5"> <b>9. Contact Information </b> </h3>
      <p class="is-size-6">
        {" "}
        If you have any questions or concerns regarding these terms and
        conditions, please contact tl-dr at vishaal.yalaman@gmail.com.{" "}
      </p>
    </div>
  );
};

export default Modal;
